[generatedPath]
dirPath = "generated"
configPath = "generated/configs/"
logPath = "generated/logs/"
outPath = "generated/out/"


[info]
prodPort = "9000"
databases = {"accountsdb"="postgresql://admin:admin@localhost:5432/accountsdb?sslmode=disable","postgresdb"="postgresql://admin:admin@localhost:5432/postgresdb?sslmode=disable"}
requestPath = "../tester/reqlog_demo.json"

[stable]
port = "9003"
bin = "./../bankofanthos/bankofanthos_demo"
config = "../bankofanthos/weaver.toml"

[canary]
port = "9004"
bin = "./../bankofanthos/bankofanthos_demo_bug1"
config = "../bankofanthos/weaver.toml"
